apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    owner: Braulio
  name: nginx-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
      owner: Braulio
  template:
    metadata:
      labels:
        app: nginx
        owner: Braulio
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
